# Generated by Django 4.2.1 on 2023-05-28 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime)),
            ],
        ),
    ]
